### ISSUE TITLE
Why do you choose to use blender to render condition images?

### ISSUE THREAD

**Issue by hangg7** [fudan-generative-vision/champ#57]
Hi dear author @Leoooo333,

Thanks for releasing your code and provide guidance in preparing condition images to run with your method!

I noticed that you use pyrender as in HMR2 for semantic condition rendering and blender for rendering the rest of conditions. I am wondering why do you make this choice -- is it intentional? Will there be any issue we should keep in mind if we only use, say, pyrender to render all conditions?

Thanks!
Hang

**Comment by Leoooo333** [comment]
Hi @hangg7! We use Blender to render all conditions.

The pyrender in HMR2 is actually to visualize the overlay semantic map onto the reference image so that users can check and adjust its SMPL's shape parameters in `--figure_scale`. For example, given an extremely fat man image, the SMPL predicted from `4D-Humans` may not perfectly match his figure. When running the SMPL Inference script, the pyrender will render the semantic map and save the overlay results under `reference_imgs_folder/visualized_imgs`, where users can check and then manually adjust `--figure_scale` if needed.

Since there are some engineering problems inside SMPL & Rendering part, we haven't PR it now. We are trying to fix it and aim to release it within this week.

**Comment by hangg7** [comment]
Thank you for your quick reply! Now if we want to render conditions without blender, is it possible to do it, as long as we align with your blender script, or is there something we should keep in mind other than aligning the rendering logic (e.g. how do you set cameras and things like that)?

**Comment by Leoooo333** [comment]
@hangg7 Yeah I think so. All of the renderer settings (including the camera) are in that blender file and rendering script. It's the same camera setting with `4D-Humans`, with the camera fixed at the origin and facing to +Y axis. By the way, seems like you have a faster renderer. We are welcome to contribute!👏

**Comment by hangg7** [comment]
Would be love to contribute what I can. I am looking at your own branch and maybe I can submit some PR there. Closing this!
